# Generated by Django 4.2.6 on 2023-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_alter_item_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="present_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="recent_purchase_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
