# Generated by Django 4.2.4 on 2023-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_item_present_quantity_item_recent_purchase_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
